In [2]:
# RMSE - Root Mean Squared Error

In [3]:
import pandas as pd
import numpy as np

In [4]:
proj_df = pd.read_csv('../NBA Projection/total_stats_df.csv')
proj_df.head()

,player_id,proj_season_id,proj_pts,proj_min,proj_fgm,proj_fga,proj_fg3m,proj_fg3a,proj_ftm,proj_fta,...,ftm,fta,ft_pct,oreb,dreb,ast,tov,stl,blk,pts
0,203932,2018-19,16.063873,33.942109,5.956650,13.509175,1.402502,3.961834,2.800268,3.608475,...,2.4,3.2,0.731,1.7,5.7,3.7,2.1,0.7,0.7,16.0
1,201143,2018-19,12.340232,30.246673,4.860939,10.359166,1.127251,3.079483,1.470858,1.927194,...,1.1,1.4,0.821,1.8,5.0,4.2,1.5,0.9,1.3,13.6
2,202329,2018-19,9.784116,27.978945,3.574506,8.190519,1.407756,3.877699,1.238291,1.679742,...,1.9,2.1,0.867,1.4,6.1,1.3,0.9,0.8,0.4,9.4
3,202692,2018-19,8.349126,20.803754,3.014837,7.286938,0.692337,2.190524,1.667793,2.166992,...,1.8,2.2,0.823,0.5,3.2,2.0,1.0,0.6,0.3,8.8
4,203518,2018-19,5.502404,16.998044,1.876591,4.592593,1.065089,2.800757,0.668980,0.839953,...,0.4,0.4,0.923,0.2,1.4,0.6,0.5,0.5,0.2,5.3

In [5]:
proj_df['squared_error'] = (proj_df['proj_pts'] - proj_df['pts'])**(2)

In [6]:
mse = proj_df['squared_error'].mean()

In [7]:
rmse = mse ** (1/2)
rmse

3.2816412699099744

In [8]:
proj_df['squared_error'] = (proj_df['proj_ast'] - proj_df['ast'])**(2)

In [9]:
mse = proj_df['squared_error'].mean()

In [10]:
rmse = mse ** (1/2)
rmse

1.0054918986715558

In [11]:
from sklearn.metrics import mean_squared_error
from math import sqrt

In [13]:
player_proj = pd.read_csv('../NBA Projection/total_stats_df.csv')
player_info = pd.read_csv('../NBA Projection/player_info_df.csv')

In [14]:
player_proj.sample(5)

,player_id,proj_season_id,proj_pts,proj_min,proj_fgm,proj_fga,proj_fg3m,proj_fg3a,proj_ftm,proj_fta,...,ftm,fta,ft_pct,oreb,dreb,ast,tov,stl,blk,pts
267,204456,2018-19,5.726172,20.815595,2.307575,5.623564,0.227795,0.797424,0.861577,1.097934,...,0.4,0.5,0.784,0.4,1.9,3.4,1.2,1.0,0.2,6.4
199,101107,2018-19,8.082661,24.961833,2.936405,7.004656,1.356273,3.657501,0.883778,1.134155,...,0.9,1.1,0.767,1.0,4.4,1.2,0.6,0.9,0.8,10.1
244,201937,2018-19,12.041572,28.677710,4.268700,9.623987,1.179710,3.195634,2.374711,2.829801,...,2.9,3.4,0.855,0.5,3.1,6.1,2.6,1.3,0.1,12.7
111,202697,2018-19,7.154616,21.015729,2.603803,6.196411,0.837985,2.570074,1.059656,1.420669,...,0.6,0.7,0.800,0.4,2.5,1.8,0.8,1.0,0.4,7.5
157,1626147,2018-19,6.405823,17.181547,2.378163,5.769303,0.877976,2.655261,0.765923,0.994947,...,0.5,0.7,0.743,0.5,1.3,0.5,0.5,0.5,0.3,3.7

In [15]:
#loc format is loc[rows, column] : represents all
df_real = player_proj.loc[:, ['pts','min','fgm','fga','fg3m','fg3a','ftm','fta','oreb','dreb','ast','stl','tov', 'blk']]

In [16]:
df_proj = player_proj.loc[:, ['proj_pts','proj_min','proj_fgm','proj_fga','proj_fg3m','proj_fg3a','proj_ftm','proj_fta','proj_oreb','proj_dreb','proj_ast','proj_stl','proj_tov', 'proj_blk']]

In [17]:
df_real.sample(5)

,pts,min,fgm,fga,fg3m,fg3a,ftm,fta,oreb,dreb,ast,stl,tov,blk
1,13.6,29.0,5.7,10.6,1.1,3.0,1.1,1.4,1.8,5.0,4.2,0.9,1.5,1.3
266,13.9,33.4,6.0,10.1,0.0,0.0,1.8,3.7,4.9,4.6,1.6,1.5,1.7,1.0
178,3.5,8.2,1.5,3.0,0.0,0.3,0.4,0.5,0.6,2.0,1.2,0.2,0.7,0.6
161,24.4,33.0,8.8,17.1,1.8,4.6,4.9,5.8,3.4,9.0,3.4,0.9,3.1,1.6
31,21.0,33.9,8.2,17.8,2.4,6.4,2.3,2.7,0.9,3.1,3.0,0.8,1.5,0.4

In [18]:
df_proj.sample(5)

,proj_pts,proj_min,proj_fgm,proj_fga,proj_fg3m,proj_fg3a,proj_ftm,proj_fta,proj_oreb,proj_dreb,proj_ast,proj_stl,proj_tov,proj_blk
109,7.512242,19.855444,2.927462,6.474419,1.024194,2.701226,0.609156,0.756756,0.494894,1.780230,1.241915,0.490405,0.637697,0.256863
68,4.317966,14.047457,1.728003,3.318841,0.000000,0.024655,0.887474,1.429816,1.143248,1.939336,0.284837,0.259949,0.727491,0.844871
56,11.289701,29.444277,4.316441,9.696499,0.968396,2.619985,1.709424,2.130907,0.431982,1.971310,4.361595,1.138828,1.469852,0.172779
229,8.962499,27.550404,3.346961,8.272636,1.080321,3.127912,1.167943,1.578989,0.797341,2.497167,2.665854,1.238101,1.328047,0.318734
81,17.833395,33.339648,6.673435,12.898568,0.012212,0.113426,4.412514,6.440222,2.581791,6.853542,2.443801,0.746683,2.245270,1.856781

In [19]:
se = mean_squared_error(df_real, df_proj)
mse = np.mean(se)
rmse = np.sqrt(mse)
confidence = rmse

print('{0} percent confidence in projected {1} per game stats'.format(100 - round(confidence, 2), '2018-19'))

98.02 percent confidence in projected 2018-19 per game stats

In [21]:
df_real_stats = pd.concat([player_info, df_real], axis=1)

In [22]:
df_real_stats.sample(5)

,player_name,player_id,proj_season_id,pts,min,fgm,fga,fg3m,fg3a,ftm,fta,oreb,dreb,ast,stl,tov,blk
175,Jonas Jerebko,201973,2018-19,8.0,29.8,3.5,6.4,0.2,0.8,0.9,1.5,1.1,4.7,3.0,1.3,1.3,0.9
57,D'Angelo Russell,1626156,2018-19,6.5,19.3,2.5,5.1,0.5,1.5,1.1,1.7,0.8,2.4,1.1,0.7,0.6,0.3
66,Dario Saric,203967,2018-19,15.5,29.3,5.8,14.0,1.6,4.6,2.4,2.9,0.5,3.1,4.1,0.8,2.2,0.2
290,Robin Lopez,201577,2018-19,10.9,26.8,3.8,9.2,1.6,4.6,1.7,2.2,0.6,2.4,2.9,0.9,1.4,0.5
111,Frank Kaminsky,1626163,2018-19,7.5,23.9,2.7,7.2,1.5,4.4,0.6,0.7,0.4,2.5,1.8,1.0,0.8,0.4

In [23]:
df_real_stats.rename(columns = 
                    {'proj_season_id' : 'season_id'}, inplace = True)

In [24]:
df_proj_stats = pd.concat([player_info, df_proj], axis=1)

In [25]:
df_proj_stats.rename(columns = {'proj_season_id':'season_id',
                               'proj_pts': 'pts',
                                'proj_min':'min',
                                'proj_fgm':'fgm',
                                'proj_fga':'fga',
                                'proj_fg3m':'fg3m',
                                'proj_fg3a':'fg3a',
                                'proj_ftm':'ftm',
                                'proj_fta':'fta',
                                'proj_oreb':'oreb',
                                'proj_dreb':'dreb',
                                'proj_ast':'ast',
                                'proj_stl':'stl',
                                'proj_tov':'tov',
                               'proj_blk':'blk'}, inplace = True)

In [26]:
display(df_real_stats.head(5))

,player_name,player_id,season_id,pts,min,fgm,fga,fg3m,fg3a,ftm,fta,oreb,dreb,ast,stl,tov,blk
0,Aaron Brooks,201166,2018-19,16.0,33.8,6.0,13.4,1.6,4.4,2.4,3.2,1.7,5.7,3.7,0.7,2.1,0.7
1,Aaron Gordon,203932,2018-19,13.6,29.0,5.7,10.6,1.1,3.0,1.1,1.4,1.8,5.0,4.2,0.9,1.5,1.3
2,Al Horford,201143,2018-19,9.4,28.3,3.2,7.3,1.2,3.5,1.9,2.1,1.4,6.1,1.3,0.8,0.9,0.4
3,Al Jefferson,2744,2018-19,8.8,21.5,3.0,7.4,1.0,2.6,1.8,2.2,0.5,3.2,2.0,0.6,1.0,0.3
4,Al-Farouq Aminu,202329,2018-19,5.3,19.0,1.8,5.1,1.3,4.1,0.4,0.4,0.2,1.4,0.6,0.5,0.5,0.2

In [27]:
display(round(df_proj_stats,1).head(5))

,player_name,player_id,season_id,pts,min,fgm,fga,fg3m,fg3a,ftm,fta,oreb,dreb,ast,stl,tov,blk
0,Aaron Brooks,201166,2018-19,16.1,33.9,6.0,13.5,1.4,4.0,2.8,3.6,1.6,5.1,2.0,0.9,1.6,0.7
1,Aaron Gordon,203932,2018-19,12.3,30.2,4.9,10.4,1.1,3.1,1.5,1.9,1.2,4.6,3.2,0.7,1.6,1.0
2,Al Horford,201143,2018-19,9.8,28.0,3.6,8.2,1.4,3.9,1.2,1.7,1.1,4.3,1.8,0.9,1.1,0.4
3,Al Jefferson,2744,2018-19,8.3,20.8,3.0,7.3,0.7,2.2,1.7,2.2,0.5,1.9,1.5,0.5,1.0,0.1
4,Al-Farouq Aminu,202329,2018-19,5.5,17.0,1.9,4.6,1.1,2.8,0.7,0.8,0.4,1.4,1.0,0.5,0.6,0.1